### ISSUE TITLE
Opening two Spotify tabs will cause double-applicaiton of commands

### ISSUE THREAD

**Issue by Juraj-Masiar** [jerosa/spotify-hotkeys-firefox#16]
STR:
1) open two Spotify tabs
2) press your short-key for Next track

What happened:
- Next after Next track is being played (one is skipped). It seems that the command is received by both tabs and they both will try to play Next track

What should happen:
- having multiple Spotify tabs should not affect switching tracks

**Comment by jerosa** [comment]
Hi,

Thanks for giving detailed information about how to reproduce the issue.
I hadn't considered that the user could have several Spotify tabs open. I'll modify the code to run only once.

**Comment by Juraj-Masiar** [comment]
Thank you! That will be great.
I often open several tabs with albums of some artists I want to checkout and then return back to my original playlist.

**Comment by Juraj-Masiar** [comment]
Man you are fast!!! 
Thanks! It works perfect. I should have reported it long time ago 😃.
