### ISSUE TITLE
Feature request: Increase hotkey range and allow faster input by capturing keystroke instead of using textfields.

### ISSUE THREAD

**Issue by MaskyS** [jerosa/spotify-hotkeys-firefox#18]
Firstly, thank you very much for writing this extension; I've been looking for a Like-song shortcut method for aeons. 

It'd be cool if the extension could record the keystroke(s) instead of having the textfield+checkbox interface! I'd love to contribute to making this happen, but I haven't done extensions before. Do you have an idea of where I'd start?

**Comment by jerosa** [comment]
Hi! Glad to know that it's helpful to you.

Actually Firefox implemented a way to handle shortcuts the way you mentioned. If you go to "about:addons" and click on "Manage Extensions Shortcuts" you can edit them with keystrokes.
Before there wasn't a way to customize the shortcuts so I used this [library](https://github.com/piroor/webextensions-lib-shortcut-customize-ui) to do it.
Maybe you can try to add key listeners to do something similar.

![image](https://user-images.githubusercontent.com/11210989/91550897-928f0980-e929-11ea-8adc-bca755d6c65b.png)
