### ISSUE TITLE
[SUGGESTION] Now playing pop-up

### ISSUE THREAD

**Issue by avi2323232323** [jerosa/spotify-hotkeys-firefox#20]
Hello :)
First of wanted to say the add-on is great, and works perfectly fine for me.
I thought about a suggestion you can add to it.
A toggleable option, that when enabled, shows a pop-up every time a track ends and a new tracks start.
If possible it can pop from the add-on on the toolbar, or as a notification.
Also, when clicking on the add-on it can show whats playing and view something like a mini-player with some info (length, album etc.).

That's all, if I knew add-on development i would contribute more, maybe in the future.
Thanks! =)

**Comment by jerosa** [comment]
Hi! I'm glad to know that the extension helps you.

Is an interesting feature to add. A pop-up might be the best. I don't really know how to do it but I'll look into the docs. 

And sure! Feel free to participate.

**Comment by avi2323232323** [comment]
I saw that you added it. Thank you very much!!

**Comment by jerosa** [comment]
Right now the notification is very simple because Firefox only have the "basic" type. In another iteration some enhancement could be made by adding interactive buttons or more information of the song as its duration, although for the moment I think it is enough.
