### ISSUE TITLE
Support music.youtube.com

### ISSUE THREAD

**Issue by marcbelmont** [jerosa/spotify-hotkeys-firefox#21]
It would be great if this extension worked with music.youtube.com.

**Comment by jerosa** [comment]
Hi, I understand that it would be very useful to implement the control for other platforms, but this extension is focused exclusively on Spotify. At the moment there are no plans to add support for more platforms.
There may be extensions that can serve your purpose in the addon repository.

**Comment by marcbelmont** [comment]
I understand. I'm closing the issue.
