### ISSUE TITLE
BUG: some shortcuts stopped working

### ISSUE THREAD

**Issue by KArlkackt** [jerosa/spotify-hotkeys-firefox#22]
Some shortcuts don't work anymore, possibly broken by a firefox update?

These features don't work anymore:
- Play/Pause
- Previous track
- Shuffle playlist
- Play/pause the current playlist/album
- Save track

These still work:
- Next track
- Repeat playlist
- Mute/Unmute

**Comment by jerosa** [comment]
Hi, thanks for the report. It seems that Spotify did some changes in the web so the button query is not working. I'll look into it.

**Comment by jerosa** [comment]
They decided to change the buttons class to some randomized CSS classes..
![imagen](https://user-images.githubusercontent.com/11210989/100788852-f556dc00-3415-11eb-9486-5db80305059d.png)

**Comment by KArlkackt** [comment]
I remembered, that I once had a working solution to control the spotify media buttons. After digging around I found out, that this solution just used to count the elements and clicked the buttons corresponding to their appearance in the DOM:

`chrome.tabs.executeScript(tab.id, {code: "(document.getElementsByClassName('player-controls__buttons')[0].childNodes[" + command + "]).click();" `

This still works, but may not be as clean of a solution as you had. If you don't find any other way you could do a similar aproach.

**Comment by jerosa** [comment]
For the moment I will query the buttons by their title. If its title is not something static then I will use your idea.

**Comment by jerosa** [comment]
I uploaded a new version but then I realized that this fix will only works on browsers with English language. I'll take the indexes approach.

**Comment by jerosa** [comment]
Uploaded version 1.5.2 and should work. Closing the issue
