### ISSUE TITLE
arrow keys as shortcuts

### ISSUE THREAD

**Issue by midros** [jerosa/spotify-hotkeys-firefox#23]
when I try to enter arrow keys as shortcuts in the settings page nothing happens.
Is there any workaround?

(same thing with Home, End, PageUp, PageDown)

**Comment by jerosa** [comment]
Where are you trying to change the shortcuts? Currently there are two ways to do this, a custom through the options page (deprecated and will disappear in future versions) and the other official way that is shown in the following link: https://github.com/jerosa/spotify-hotkeys-firefox#customizing-the-shortcuts

Try again following that guide and should work

**Comment by midros** [comment]
yes you are right I was trying through the options page
everything works fine now

thanks a lot
