### ISSUE TITLE
Automatic key press

### ISSUE THREAD

**Issue by docop** [jerosa/spotify-hotkeys-firefox#28]
Hi  Very great extension and while it give good used, for finding good song or so, can it be possible to add an automatic function ? As to skip .. have a <keyboard shortcut> that will be automaticaly press every 30sec ..  That can be quite great.

Thanks in advance and happy new year.

**Comment by jerosa** [comment]
Hi! Thx for the kind words. However, the feature you are requesting is a bit strange. Why would you want to skip the songs every x seconds? The usefulness of this extension is to facilitate the management of spotify from the keyboard saving a couple of clicks, but I can't see that it is changing every few seconds, when you can do it with the keyboard if a song is not to your liking.

**Comment by docop** [comment]
It's more to find what is good. Let say a new category. Having all song play for like 20sec.. and when you see a good one, then you click to stop the 'shuffle preview mode'
