### ISSUE TITLE
Error possibly due to new Spotify web design

### ISSUE THREAD

**Issue by HeiMar4** [jerosa/spotify-hotkeys-firefox#29]
Hi,

I love your add-on and use it together with auto-hotkey on a regular basis. Lately it doesn't recognize the hotkeys anymore. The add-on debugger throws an error:

***Error: document.querySelectorAll(...)[2] is undefined***

in background.js line 106 when trying to trigger playpause. Analysing the Spotify web player page I'm guessing the controls have been renamed/redesigned. 

Could you please look into this? And thank you in advance

**Comment by jerosa** [comment]
They changed (again) the ids and CSS classes and broke everything. I'll try to fix them thanks for the report!

**Comment by HeiMar4** [comment]
Thanks for the quick response! Working again!

**Comment by jerosa** [comment]
Hi @CyanSlinky sorry about still having issues with the volume bar. I've only been able to fix the basic controls while the volume slider isn't that easy, They changed something in the inside that the event isn't being recognized but the value of the input yes.

The global hotkeys is something that other browsers allow. However Firefox doesn't and the workaround is to use auto-hotkey.

I'll create another issue and try to solve it, but without ETA.

**Comment by jerosa** [comment]
See #31
